trigger:
- main # Run pipeline on changes to 'main' branch

pool:
  vmImage: 'ubuntu-latest' # Use Ubuntu agent

steps:
# Install Node.js version
- task: UseNode@2
  inputs:
    version: '16'
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    npm install
  displayName: 'Install dependencies'

# Run tests
- script: |
    npm test
  displayName: 'Run tests'

# Build the web application
- script: |
    npm run build
  displayName: 'Build web application'

# Publish artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publish build artifacts'

# # Deploy to Azure Web App (Optional Deployment Step)
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: '<your-azure-subscription>'
#     appName: '<your-app-name>'
#     package: '$(Build.ArtifactStagingDirectory)/drop'
#   displayName: 'Deploy to Azure Web App'